name: mricron

version: 1.0.20190902

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: centos:7
  pkg-manager: yum

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - wget
        - unzip
        - ca-certificates
        - gtk2
        - pigz

    - workdir: /opt

    - run:
        - wget --quiet -O MRIcon_linux.zip 'https://github.com/neurolabusc/MRIcron/releases/download/v{{ context.version }}/MRIcron_linux.zip'
        - unzip MRIcon_linux.zip
        - rm -rf MRIcon_linux.zip

    - environment:
        PATH: /opt/mricron:/opt/mricron/Resources:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:~/.local/bin

deploy:
  bins:
    - dcm2niix

readme: |-
  ----------------------------------
  ## mricron/{{ context.version }} ##
  MRIcroGL is a cross-platform tool for viewing DICOM and NIfTI format images. It provides a drag-and-drop user interface as well as a scripting language. Please see the wiki page from more details. Note that the wiki page describes version 1.0 of the software, while this Github page is for the upcoming version 1.2. The changes are in general subtle, but the scripting has changed quite a bit.


  Example:
  ```
  MRIcron
  ```

  More documentation can be found here: https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage

  To run applications outside of this container: ml mricron/{{ context.version }}

  Citation:
  ```
  Rorden C, Brett M. Stereotaxic display of brain lesions. Behav Neurol. 2000;12(4):191-200. doi: 10.1155/2000/421719. PMID: 11568431.
  ```

  ----------------------------------
