name: terastitcher
version: 1.11.10

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: fedora:35
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - curl
        - ca-certificates

    - workdir: /opt/terastitcher-1.11.10/

    - run:
        - curl -fsSL --retry 5 https://object-store.rc.nectar.org.au/v1/AUTH_dead991e1fa847e3afcca2d3a7041f5d/build/TeraStitcher-portable-1.11.10-Linux.tar.gz | tar -xz -C /opt/terastitcher-1.11.10 --strip-components 1

    - environment:
        PATH: $PATH:/opt/terastitcher-1.11.10

    - copy: test.sh /test.sh

deploy:
  path:
    - /opt/terastitcher-1.11.10/

readme: |-
  ----------------------------------
  ## TeraStitcher/{{ context.version }} ##
  TeraStitcher is a free tool that enables the stitching of Teravoxel-sized tiled microscopy images even on workstations with relatively limited resources of memory (<8 GB) and processing power. It exploits the knowledge of approximate tile positions and uses ad-hoc strategies and algorithms designed for such very large datasets. The produced images can be saved into a multiresolution representation to be efficiently visualized (e.g. Vaa3D-TeraFly) and processed.


  Example:
  ```
  ```

  More documentation can be found here: http://abria.github.io/TeraStitcher/

  To make the executables and scripts inside this container transparently available in the command line of environments where Neurocommand is installed (without the need to use 'Apptainer exec'): ml Name_of_Container/{{ context.version }}

  Citation:
  ```

  ```

  ----------------------------------

files:
  - name: test.sh
    contents: "# this file should contain a functional test of the tool that makes it possible to test if everything was correctly installed"
