name: slicer
version: 5.0.3

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:22.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - python3-dev
        - gcc
        - libopenslide0
        - curl
        - ca-certificates
        - libxdamage1
        - libpulse-dev
        - libnss3
        - libglu1-mesa
        - libsm6
        - libxrender1
        - libxt6
        - libxcomposite1
        - libfreetype6
        - libasound2
        - libfontconfig1
        - libxkbcommon0
        - libxcursor1
        - libxi6
        - libxrandr2
        - libxtst6
        - libqt5svg5-dev
        - wget
        - libqt5opengl5-dev
        - libqt5opengl5
        - libqt5gui5
        - libqt5core5a

    - template:
        name: miniconda
        conda_install: pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
        version: latest

    - run:
        - pip install h11==0.11 monailabel

    - run:
        - curl -fsSL --retry 5 https://download.slicer.org/bitstream/62cc52d2aa08d161a31c1af0 | tar -xz -C /opt/

    - workdir: /opt/Slicer-5.0.3-linux-amd64/NA-MIC/

    - run:
        - curl -fsSL --retry 5 https://object-store.rc.nectar.org.au/v1/AUTH_dead991e1fa847e3afcca2d3a7041f5d/build/MONAILabel30893.tar.gz | tar -xz -C /opt/Slicer-5.0.3-linux-amd64/NA-MIC/ --strip-components 1

    - install:
        - nvidia-cuda-toolkit

    - environment:
        PATH: /miniconda3/bin:/usr/bin:/opt/Slicer-5.0.3-linux-amd64/bin:/opt/Slicer-5.0.3-linux-amd64

deploy:
  bins:
    - Slicer
  path:
    - /opt/Slicer-5.0.3-linux-amd64/bin

readme: |-
  ----------------------------------
  ## slicer/{{ context.version }} ##
  A software application for visualization and analysis of medical image computing data sets. All commonly used data sets are supported, such as images, segmentations, surfaces, annotations, transformations, etc., in 2D, 3D, and 4D. Visualization is available on desktop and in virtual reality. Analysis includes segmentation, registration, and various quantifications.
  A research software platform, which allows researchers to quickly develop and evaluate new methods and distribute them to clinical users. All features are available and extensible in Python and C++. A full Python environment is provided where any Python packages can be installed and combined with built-in features. Slicer has a built-in Python console and can act as a Jupyter notebook kernel with remote 3D rendering capabilities.
  Product development platform, which allows companies to quickly prototype and release products to users. Developers can focus on developing new methods and do not need to spend time with redeveloping basic data import/export, visualization, interaction features. The application is designed to be highly customizable (with custom branding, simplified user interface, etc.). 3D Slicer is completely free and there are no restrictions on how it is used - it is up to the software distributor to ensure that the developed application is suitable for the intended use.

  to start the gui run: Slicer

  More documentation can be found here: https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html

  To run applications outside of this container: ml slicer/{{ context.version }}
  ----------------------------------
