name: convert3d
version: 1.0.0

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: debian:stretch
  pkg-manager: apt

  directives:
    - template:
        name: convert3d
        version: 1.0.0

    - user: neuro

deploy:
  path:
    - /opt/convert3d-1.0.0/bin/

readme: |-
  ----------------------------------
  ## convert3d/{{ context.version }} ##
  C3D is a command-line tool for converting 3D images between common file formats. The tool also includes a growing list of commands for image manipulation, such as thresholding and resampling.


  Example:
  ```
  c3d -h
  ```

  More documentation can be found here: https://sourceforge.net/p/c3d/git/ci/master/tree/doc/c3d.md

  To run container outside of this environment: ml convert3d/{{ context.version }}

  ----------------------------------
