name: mgltools
version: 1.5.7

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: centos:7
  pkg-manager: yum

  directives:
    - install:
        - curl
        - ca-certificates
        - tk
        - mesa-libGLU
        - libXmu
        - libXi
        - mesa-dri-drivers

    - run:
        - cd /opt; curl -SL https://ccsb.scripps.edu/mgltools/download/491 | tar -zx; cd mgltools_x86_64Linux2_1.5.7
        - ./install.sh -d /opt/mgltools -c 1

    - environment:
        PATH: $PATH:/opt/mgltools/bin:/

    - copy: test.sh /test.sh

deploy:
  path:
    - /opt/mgltools/bin/

readme: |-
  ----------------------------------
  ## MGLTools/{{ context.version }} ##
  Thew MGLTools software suite was developed in the Sanner lab at the Center for Computational Structural Biology (CCRB) formerly known as the Molecular Graphics Laboratory (MGL) of The Scripps Research Institute for visualization and analysis of molecular structures. Navigation portlet on the left has links to downloads, screenshots, documentation section of this website where you can find more information about MGLTools. MGLTools comprises:

  - the Python Molecular Viewer (PMV), a general purpose molecular viewer
  - AutoDockTools (ADT) a set of PMV commands specifically developed to support AutoDock users
  - Vision, a visual programming environment.

  Example:
  ```
  vision
  adt
  ```

  More documentation can be found here: https://ccsb.scripps.edu/mgltools/

  To make the executables and scripts inside this container transparently available in the command line of environments where Neurocommand is installed (without the need to use 'Apptainer exec'): ml mgltools/{{ context.version }}

  Citation:
  ```

  ```

  ----------------------------------

files:
  - name: test.sh
    contents: |-
      # this file should contain a functional test of the tool that makes it possible to test if everything was correctly installed
       adt
