name: matlab
version: 2022b

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: mathworks/matlab-deep-learning:r2022b
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - csh
        - wget
        - git
        - curl
        - ca-certificates
        - datalad
        - unzip
        - libfftw3-3
        - apt-transport-https
        - coreutils
        - cryptsetup
        - squashfs-tools
        - lua-bit32
        - lua-filesystem
        - lua-json
        - lua-lpeg
        - lua-posix
        - lua-term
        - lua5.2
        - lmod
        - imagemagick
        - less
        - nano
        - tree
        - gcc
        - libzstd1
        - zlib1g-dev
        - zip
        - build-essential
        - uuid-dev
        - libgpgme-dev
        - libseccomp-dev
        - pkg-config

    - template:
        name: miniconda
        version: latest

    - environment:
        GOPATH: $HOME/go
        MLM_LICENSE_FILE: ~/Downloads
        PATH: $PATH:/usr/local/go/bin:$PATH:/bin

    - run:
        - wget https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz
        - tar -C /usr/local -xzvf go1.17.2.linux-amd64.tar.gz
        - rm go1.17.2.linux-amd64.tar.gz
        - mkdir -p /src/github.com/sylabs
        - cd /src/github.com/sylabs
        - wget https://github.com/sylabs/singularity/releases/download/v3.9.3/singularity-ce-3.9.3.tar.gz
        - tar -xzvf singularity-ce-3.9.3.tar.gz
        - cd singularity-ce-3.9.3
        - ./mconfig --without-suid --prefix=/usr/local/singularity
        - make -C builddir
        - make -C builddir install
        - cd ..
        - rm -rf singularity-ce-3.9.3
        - rm -rf /usr/local/go
        - ln -s /usr/local/singularity/bin/singularity /bin/

    - run:
        - rm /usr/local/bin/matlab

    - copy: matlab /usr/local/bin/matlab

    - run:
        - chmod a+x /usr/local/bin/matlab
        - mkdir /opt/matlab/R2022b/licenses
        - chmod a+rwx /opt/matlab/R2022b/licenses

    - copy: module.sh /usr/share/

deploy:
  bins:
    - mex

readme: |-
  ----------------------------------
  ## matlab/{{ context.version }} ##
  Matlab IDE

  Important note about licensing
  ------------------------------

  The Matlab application includes a commercial product, and requires a MATLAB license to run. On first run, a license dialog will appear. Users should follow these steps to activate license:
  1. Choose "Activate automatically using the internet" (and press Next)
  2. Enter their institutional email address and password (and press Next)
  3. Select license to use (and press Next)
  4. A username will be displayed (just press Next)

  If the user is eligible for a MATLAB license through the institution, the license will be downloaded to the user home directory (inside the ~/.matlab folder). After the license dialog closes, it is required to re-run the Matlab application. The license will be now available for future executions of Matlab, and the dialog will not show again.

  To use the application without internet connectivity, it should also be possible to generate a license on the mathworks website, and place it in ~/Downloads (exact file name does not matter, but it should have a .lic extension). The license should be detected automatically when the Matlab application starts (no license dialog will be presented). Generating a license on the Mathworks website requires specifying username and host id. Username can be displayed in Linux by typing 'id' in the terminal. For instructions on how to find your host id, read here: https://au.mathworks.com/matlabcentral/answers/101892-what-is-a-host-id-how-do-i-find-my-host-id-in-order-to-activate-my-license?s_tid=srchtitle

  Examples
  --------

    LAUNCH INTERACTIVE IDE -

    matlab

    RUNNING SCRIPT IN BATCH -

    matlab -batch command

    COMPILYING C CODE TO WORK WITH MATLAB -

    mex

  More documentation can be found here
  ------------------------------------

    https://hub.docker.com/r/mathworks/matlab-deep-learning

    mathworks.com


  To run applications outside of this container
  ---------------------------------------------

    ml matlab/{{ context.version }}

  Citation
  --------

    (MATLAB, Mathworks Inc.)

  ----------------------------------

files:
  - name: matlab
    contents: |-
      #!/bin/bash
      export MLM_LICENSE_FILE=${HOME}/Downloads
      echo 'MLM_LICENSE_FILE='${MLM_LICENSE_FILE}
      /opt/matlab/R2022b/bin/matlab "$@"

  - name: module.sh
    contents: |-
      # system-wide profile.modules                                          #
      # Initialize modules for all sh-derivative shells                      #
      #----------------------------------------------------------------------#
      trap "" 1 2 3

      case "$0" in
          -bash|bash|*/bash) . /usr/share/lmod/6.6/init/bash ;;
             -ksh|ksh|*/ksh) . /usr/share/lmod/6.6/init/ksh ;;
             -zsh|zsh|*/zsh) . /usr/share/lmod/6.6/init/zsh ;;
                -sh|sh|*/sh) . /usr/share/lmod/6.6/init/sh ;;
                          *) . /usr/share/lmod/6.6/init/sh ;;  # default for scripts
      esac

      trap - 1 2 3
