name: mrtrix3tissue
version: 5.2.8

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ghcr.io/neurodesk/caid/fsl_6.0.3:20200905
  pkg-manager: apt

  directives:
    - template:
        name: mrtrix3tissue
        method: source
        version: master

    - template:
        name: ants
        version: 2.3.4

deploy:
  path:
    - /opt/mrtrix3tissue-master/bin/

readme: |-
  ----------------------------------
  ## mrtrix3tissue/{{ context.version }} ##
  MRtrix3Tissue is a fork of the MRtrix3 project. It adds capabilities for 3-Tissue CSD modelling and analysis to a complete version of MRtrix3. More information can be found on the official website at https://3Tissue.github.io.

  Example:
  ```
  mrview
  ```

  More documentation can be found here: https://3tissue.github.io/doc/general.html

  To run container outside of this environment: ml mrtrix3tissue/{{ context.version }}

  ----------------------------------
