name: palmettobug
version: 0.0.2

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - ca-certificates
        - wget
        - unzip
        - libx11-6
        - fontconfig
        - libgles2

    - workdir: /opt

    - template:
        name: miniconda
        conda_install: python=3.9
        version: latest

    - run:
        - wget https://object-store.rc.nectar.org.au/v1/AUTH_dead991e1fa847e3afcca2d3a7041f5d/build/CIPHER-main-20250120.zip
        - unzip CIPHER-main-20250120
        - rm -rf CIPHER-main-20250120
        - cd CIPHER-main
        - pip install .
        - cd ..
        - rm -rf CIPHER-main

deploy:
  bins:
    - palmettobug

readme: |-
  ----------------------------------
  ## palmettobug/{{ context.version }} ##
  CIPHER is a pure-python GUI in customtinker that, along with its sister package isoSegDenoise, can preprocess, segment, and analyze high-dimensional image or flow cytometry data, especially mass cytometry / imaging mass cytometry data

  Example:
  ```
  palmettobug
  ```

  More documentation can be found here: https://github.com/immunecells/CIPHER/tree/main

  Citation:
  ```
  TBD
  ```

  To run container outside of this environment: ml palmettobug/{{ context.version }}

  WARNING: THIS TOOL CURRENLTY ALTERS .fonts directory and messes up the fonts in Neurodesk terminals. Needs to be removed when container stops.

  ----------------------------------
